#!/usr/bin/fish
# shellcheck disable=SC1071

# Startup script executes once as the web terminal is loaded

set -Ux fish_greeting ""

# Run these commands only if in docker container
if test -f /.dockerenv
    alias -s docker "sudo docker"
    set -Ux HOST_PATH "$(docker inspect labenv | jq -r '.[0].Mounts[] | select(.Destination=="/home/ubuntu") | .Source')"
    set -Ux HOST_USERNAME "$(docker system info --format '{{.Name}}')"
    set -Ux NETWORK_GATEWAY "$(docker inspect lab_net | jq -r '.[0].IPAM.Config.[0].Gateway')"
end

mkdir -p /home/ubuntu/recordings

while true
    set DATE_TIME (env TZ=Europe/Moscow date '+%Y-%m-%d_%H-%M-%S')

    asciinema rec -i 1 "/home/ubuntu/recordings/$DATE_TIME.cast" -c zellij

    read -P "Session finished. Press Enter to restart or type 'exit' to quit: " confirm
    if test "$confirm" = "exit"
        break
    end
end
