FROM node:24-bookworm

WORKDIR /app

RUN apt-get update \
    && apt-get install -y openssh-client sshpass sudo fish jq \
    && wget https://download.docker.com/linux/static/stable/x86_64/docker-29.1.3.tgz \
    && tar -xzf docker-29.1.3.tgz && mv ./docker/* /usr/local/bin \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json .

RUN npm i

EXPOSE 3000

COPY . .

CMD ["/app/scripts/cmd.sh"]
